### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by mezgoodle** [Dinislames/JavaScript#1]
https://github.com/Dinislames/JavaScript/blob/367b699e1e18d723872d577e89a6b1f9fd0a887c/index.js#L4

Hi. Never **show** your token public. It`s a security problem and you can **lose** control of your bot.

**Comment by Dinislames** [comment]
Greetings, thank you for your advice. 

&gt; Понедельник, 13 апреля 2020, 21:00 +03:00 от Maxim Zavalniuk :
&gt; 
&gt; 
&gt; https://github.com/Dinislames/JavaScript/blob/367b699e1e18d723872d577e89a6b1f9fd0a887c/index.js#L4
&gt; Hi. Never  show your token public. It`s a security problem and you can  lose control of your bot.
&gt; —
&gt; You are receiving this because you are subscribed to this thread.
&gt; Reply to this email directly,  view it on GitHub , or  unsubscribe .

**Comment by mezgoodle** [comment]
> 
> Greetings, thank you for your advice. &gt; Понедельник, 13 апреля 2020, 21:00 +03:00 от Maxim Zavalniuk : &gt; &gt; &gt; https://github.com/Dinislames/JavaScript/blob/367b699e1e18d723872d577e89a6b1f9fd0a887c/index.js#L4 &gt; Hi. Never show your token public. It`s a security problem and you can lose control of your bot. &gt; — &gt; You are receiving this because you are subscribed to this thread. &gt; Reply to this email directly, view it on GitHub , or unsubscribe .

Also, if you showed the token, you can generate a new one by @BotFather settings
